png("plot3.png", height = 480, width = 480)
plot(data_set$Sub_metering_1~data_set$DateTime, type = "l", ylab = "Energy sub metering", xlab = "")
lines(data_set$DateTime, data_set$Sub_metering_2, col = "red")
lines(data_set$DateTime, data_set$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, lwd = 2, col=c("black", "red", "blue"))
dev.off()