png("plot4.png", height = 480, width = 480)
par(mfrow = c(2, 2))
plot(data_set$Global_active_power~data_set$DateTime, type = "l", ylab = "Global Active Power", xlab = "")
plot(data_set$Voltage~data_set$DateTime, type = "l", ylab = "Voltage", xlab = "DateTime")
plot(data_set$Sub_metering_1~data_set$DateTime, type = "l", ylab = "Energy sub metering", xlab = "")
lines(data_set$DateTime, data_set$Sub_metering_2, col = "red")
lines(data_set$DateTime, data_set$Sub_metering_3, col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, lwd = 2, col=c("black", "red", "blue"), bty="n")
plot(data_set$Global_reactive_power~data_set$DateTime, type = "l", ylab = "Global_reactive_power", xlab = "DateTime")  
dev.off()